using System.Text;
using Zipper.Profiles;
using Zipper.Utils;

namespace Zipper.LoadFiles;

/// <summary>
/// Writes a column-profile-driven DAT load file for loadfile-only mode.
/// Headers and column order are determined entirely by the ColumnProfile;
/// row values are generated by DataGenerator using synthetic file metadata.
/// </summary>
internal sealed class ProfileDrivenDatWriter : LoadFileWriterBase
{
    public override string FormatName => "DAT (Profile)";

    public override string FileExtension => ".dat";

    public override async Task WriteAsync(
        Stream stream,
        FileGenerationRequest request,
        List<FileData> processedFiles,
        ChaosEngine? chaosEngine = null)
    {
        var profile = request.Metadata.ColumnProfile
            ?? throw new InvalidOperationException("ProfileDrivenDatWriter requires a ColumnProfile on the request.");

        var encoding = EncodingHelper.GetEncodingOrDefault(request.LoadFile.Encoding);
        var eolString = GetEolString(request.Delimiters.EndOfLine);
        char colDelim = !string.IsNullOrEmpty(request.Delimiters.ColumnDelimiter)
            ? request.Delimiters.ColumnDelimiter[0] : '\u0014';
        char quote = !string.IsNullOrEmpty(request.Delimiters.QuoteDelimiter)
            ? request.Delimiters.QuoteDelimiter[0] : '\u00fe';
        bool hasQuote = !string.IsNullOrEmpty(request.Delimiters.QuoteDelimiter);

        var generator = new DataGenerator(profile, request.Metadata.Seed);
        var columnNames = generator.GetColumnNames().ToList();

        // Write header row
        var header = BuildProfileHeader(columnNames, colDelim, quote, hasQuote, profile.FieldNamingConvention);

        // Separate Random for synthetic file sizes / page counts so it does not
        // interleave with the DataGenerator's own seeded random stream.
#pragma warning disable S2245
        var rowRandom = request.Metadata.Seed.HasValue
            ? new Random(request.Metadata.Seed.Value + 17)
            : new Random();
#pragma warning restore S2245

        var context = new ProfileWriterContext(
            stream,
            request,
            encoding,
            eolString,
            colDelim,
            quote,
            hasQuote,
            generator,
            columnNames,
            header,
            rowRandom);

        if (chaosEngine == null)
        {
            await this.WriteWithoutChaosAsync(context);
        }
        else
        {
            await this.WriteWithChaosAsync(context, chaosEngine);
        }
    }

    private async Task WriteWithoutChaosAsync(ProfileWriterContext context)
    {
        var preamble = context.Encoding.GetPreamble();
        if (preamble.Length > 0)
        {
            await context.Stream.WriteAsync(preamble, 0, preamble.Length);
        }

        await context.Stream.WriteAsync(context.Encoding.GetBytes(context.Header + context.EolString));

        var buffer = new StringBuilder();

        for (long i = 1; i <= context.Request.Output.FileCount; i++)
        {
            var line = GenerateRowLine(context, i);
            buffer.Append(line);
            buffer.Append(context.EolString);

            if (buffer.Length > 200_000)
            {
                await context.Stream.WriteAsync(context.Encoding.GetBytes(buffer.ToString()));
                buffer.Clear();
            }
        }

        if (buffer.Length > 0)
        {
            await context.Stream.WriteAsync(context.Encoding.GetBytes(buffer.ToString()));
        }
    }

    private async Task WriteWithChaosAsync(ProfileWriterContext context, ChaosEngine chaosEngine)
    {
        var rows = new List<(long LineNumber, string RecordId, string Line)>();
        rows.Add((1, "HEADER", context.Header));

        for (long i = 1; i <= context.Request.Output.FileCount; i++)
        {
            long lineNumber = i + 1;
            var recordId = $"DOC{i:D8}";
            var line = GenerateRowLine(context, i);
            rows.Add((lineNumber, recordId, line));
        }

        await WriteRowsWithChaosAsync(context.Stream, context.Encoding, context.EolString, rows, chaosEngine);
    }

    private static string GenerateRowLine(ProfileWriterContext context, long i)
    {
        var fileType = context.Request.Output.FileTypeLower;
        var folderNum = (int)((i - 1) % 50) + 1;
        var workItem = new FileWorkItem
        {
            Index = i,
            FolderNumber = folderNum,
            FilePathInZip = $"NATIVES/{folderNum:D3}/DOC{i:D8}.{fileType}",
        };

        var fileData = new FileData
        {
            WorkItem = workItem,
            DataLength = context.RowRandom.Next(1024, 10_485_760),
            PageCount = context.RowRandom.Next(1, 11),
        };

        var values = context.Generator.GenerateRow(workItem, fileData);
        return BuildProfileRow(values, context.ColumnNames, context.ColDelim, context.Quote, context.HasQuote, context.Request.Delimiters.NewlineDelimiter);
    }

    private sealed record ProfileWriterContext(
        Stream Stream,
        FileGenerationRequest Request,
        Encoding Encoding,
        string EolString,
        char ColDelim,
        char Quote,
        bool HasQuote,
        DataGenerator Generator,
        List<string> ColumnNames,
        string Header,
        Random RowRandom);

    private static string BuildProfileHeader(
        List<string> columnNames,
        char colDelim,
        char quote,
        bool hasQuote,
        string? namingConvention)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var name in columnNames)
        {
            if (!first)
            {
                sb.Append(colDelim);
            }

            var finalName = NamingConventionHelper.ApplyConvention(name, namingConvention);
            AppendField(sb, finalName, quote, hasQuote);
            first = false;
        }

        return sb.ToString();
    }

    private static string BuildProfileRow(
        Dictionary<string, string> values,
        List<string> columnNames,
        char colDelim,
        char quote,
        bool hasQuote,
        string newlineDelimiter)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var name in columnNames)
        {
            if (!first)
            {
                sb.Append(colDelim);
            }

            var value = values.TryGetValue(name, out var v) ? v : string.Empty;
            AppendField(sb, EscapeDatField(value, quote, newlineDelimiter), quote, hasQuote);
            first = false;
        }

        return sb.ToString();
    }
}
