using System.Text;
using Zipper.Profiles;

namespace Zipper.LoadFiles;

/// <summary>
/// Writes a column-profile-driven DAT load file for loadfile-only mode.
/// Headers and column order are determined entirely by the ColumnProfile;
/// row values are generated by DataGenerator using synthetic file metadata.
/// </summary>
internal sealed class ProfileDrivenDatWriter : LoadFileWriterBase
{
    public override string FormatName => "DAT (Profile)";

    public override string FileExtension => ".dat";

    public override async Task WriteAsync(
        Stream stream,
        FileGenerationRequest request,
        List<FileData> processedFiles,
        ChaosEngine? chaosEngine = null)
    {
        var profile = request.Metadata.ColumnProfile
            ?? throw new InvalidOperationException("ProfileDrivenDatWriter requires a ColumnProfile on the request.");

        var encoding = EncodingHelper.GetEncodingOrDefault(request.LoadFile.Encoding);
        var eolString = GetEolString(request.Delimiters.EndOfLine);
        char colDelim = !string.IsNullOrEmpty(request.Delimiters.ColumnDelimiter)
            ? request.Delimiters.ColumnDelimiter[0] : '\u0014';
        char quote = !string.IsNullOrEmpty(request.Delimiters.QuoteDelimiter)
            ? request.Delimiters.QuoteDelimiter[0] : '\u00fe';
        bool hasQuote = !string.IsNullOrEmpty(request.Delimiters.QuoteDelimiter);

        var generator = new DataGenerator(profile, request.Metadata.Seed);
        var columnNames = generator.GetColumnNames().ToList();

        // Write header row
        var header = BuildProfileHeader(columnNames, colDelim, quote, hasQuote);
        await stream.WriteAsync(encoding.GetBytes(header + eolString));

        // Separate Random for synthetic file sizes / page counts so it does not
        // interleave with the DataGenerator's own seeded random stream.
#pragma warning disable S2245
        var rowRandom = request.Metadata.Seed.HasValue
            ? new Random(request.Metadata.Seed.Value + 17)
            : new Random();
#pragma warning restore S2245

        var fileType = request.Output.FileTypeLower;
        var buffer = new StringBuilder();

        for (long i = 1; i <= request.Output.FileCount; i++)
        {
            var folderNum = (int)((i - 1) % 50) + 1;
            var workItem = new FileWorkItem
            {
                Index = i,
                FolderNumber = folderNum,
                FilePathInZip = $"NATIVES/{folderNum:D3}/DOC{i:D8}.{fileType}",
            };

            var fileData = new FileData
            {
                WorkItem = workItem,
                DataLength = rowRandom.Next(1024, 10_485_760),
                PageCount = rowRandom.Next(1, 11),
            };

            var values = generator.GenerateRow(workItem, fileData);
            var line = BuildProfileRow(values, columnNames, colDelim, quote, hasQuote);
            buffer.Append(line);
            buffer.Append(eolString);

            if (buffer.Length > 200_000)
            {
                await stream.WriteAsync(encoding.GetBytes(buffer.ToString()));
                buffer.Clear();
            }
        }

        if (buffer.Length > 0)
        {
            await stream.WriteAsync(encoding.GetBytes(buffer.ToString()));
        }
    }

    private static string BuildProfileHeader(
        List<string> columnNames,
        char colDelim,
        char quote,
        bool hasQuote)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var name in columnNames)
        {
            if (!first)
            {
                sb.Append(colDelim);
            }

            MetadataRowBuilder.AppendField(sb, name, quote, hasQuote);
            first = false;
        }

        return sb.ToString();
    }

    private static string BuildProfileRow(
        Dictionary<string, string> values,
        List<string> columnNames,
        char colDelim,
        char quote,
        bool hasQuote)
    {
        var sb = new StringBuilder();
        bool first = true;
        foreach (var name in columnNames)
        {
            if (!first)
            {
                sb.Append(colDelim);
            }

            var value = values.TryGetValue(name, out var v) ? v : string.Empty;
            MetadataRowBuilder.AppendField(sb, value, quote, hasQuote);
            first = false;
        }

        return sb.ToString();
    }
}
