name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Zipper/Zipper.csproj

    - name: Build for Windows x64
      run: dotnet publish Zipper/Zipper.csproj -c Release -r win-x64 --self-contained true -o publish/win-x64

    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: zipper-win-x64
        path: publish/win-x64

    - name: Build for Linux x64
      run: dotnet publish Zipper/Zipper.csproj -c Release -r linux-x64 --self-contained true -o publish/linux-x64

    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: zipper-linux-x64
        path: publish/linux-x64

    - name: Build for macOS ARM64
      run: dotnet publish Zipper/Zipper.csproj -c Release -r osx-arm64 --self-contained true -o publish/osx-arm64

    - name: Upload macOS ARM64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: zipper-osx-arm64
        path: publish/osx-arm64
